services:
  backend:
    build:
      context: ..
      dockerfile: src/Dockerfile
    image: ${DOCKERHUB_USERNAME:-username}/omnipass-backend:latest
    container_name: omnipass-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME:-username}/omnipass-frontend:latest
    ports:
      - "80:80"
