[project]
name = "OmniPass"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]==0.139.0",
    "httpx==0.28.1",
    "pydantic==2.13.4",
    "pydantic-settings==2.3.0",
    "python-dotenv==1.2.2",
    "uvicorn==0.50.2",
]
