name: "Release OmniPass Extension"
on:
  workflow_dispatch:
  push:
    tags:
      - "v-ex-*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Debug - Show Directory Structure
        run: |
          echo "Current directory:"
          pwd
          echo -e "\nRepo structure:"
          ls -la
          echo -e "\nLooking for extension directories:"
          find . -type d -name "*extension*" 2>/dev/null

      - name: Zip Extension
        run: |
          cd frontend
          cd extenstion
          zip -r omnipass_extension.zip .

      - name: Create a Github Release
        uses: softprops/action-gh-release@v1
        with:
          name: Extension Release ${{ github.ref_name }}
          files: frontend/extension/omnipass_extension.zip
          generate_release_notes: true
